### ISSUE TITLE
Assignment 3 Issue

### ISSUE THREAD

**Issue by ewallen88** [RaviAsapu/Interview_Challenge#1]
Hey Ravi, thanks for working on this. Having an issue with Assignment 3, do you mind patching (or updating the documentation) so this'll work?

Here's the output from my CLI:

C:\Users\ewall\Desktop\Ravi\employeeCRUD>npm start

> employeecrud@1.0.0 start C:\Users\ewall\Desktop\Ravi\employeeCRUD
> nodemon assignment3

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node assignment3.js`
Server failed to start due to error: SequelizeAccessDeniedError: Access denied for user 'root'@'localhost' (using password: YES)
[nodemon] clean exit - waiting for changes before restart

**Comment by RaviAsapu** [comment]
Hi Eric,
Apologies for this, I have used 'root' as a  password to connect to MySQL,  because of this it is not allowing to connect to server. Now I have created AWS free tier db, now it will work as expected.
